language: java
jdk:
  - openjdk8

branches:
  only:
    - dev

cache:
  directories:
    - '/$HOME/.m2/repository'
    - '/$HOME/.gradle'

script: "./gradlew clean build"
before_install:
  chmod +x gradlew

notifications:
  email:
    recipients:
      - dmsgml9903@gmail.com
